const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log('Clearing old products and types...');
  await prisma.product.deleteMany({});
  await prisma.productType.deleteMany({});

  console.log('Seeding new product types...');
  const typesData = [
    "ACRYLIC", "ACRYLIC COMPLETE DENTURE", "ACRYLIC FACING", "BILATERAL DENTURE FRAME", "BITE RIMS", 
    "BITE SPLINT", "BLEACHING TRAY", "CEMENT RETAIN PFM", "CERAMIC", "COLD CURE REPAIR", 
    "DUPLICATION OF CASTS", "DURACETAL PARTIAL DENTURE", "DURAFLEX PARTIAL DENTURE", "EMAX VENEER", 
    "FLEXIBLE", "FLEXIBLE RPD BITE RIM U/L", "FLEXIBLE RPD REPAIR", "FULL METAL", 
    "FULL PALATAL COVERAGE FRAME", "HABIT BREAKER", "HAWLEY'S APPLIANCE", 
    "HAWLY'S APPLIANCE WITH EXPANSION SCREW", "HYBRID DENTURE", "IN LAY", "MATERIALS", "METAL", 
    "METAL TRAIL", "MONILITHIUM", "ORTHO", "ORTHO RETRACTER", "PFM", "PFM FACING", "SCAN", 
    "SOLDERED TPA MOLAR TUBE", "SPACE MAINTAINER REPAIR", "SPACE MAINTAINER WITH RPD", 
    "STUDY MODEL", "ZIRCON CORE CUTBACK", "ZIRCON REPAIR", "ZIRCONIUM"
  ];

  for (const name of typesData) {
    await prisma.productType.create({ data: { name } });
  }

  console.log('Seeding new products...');
  const productsRaw = [
    "2D EXPANSION SCREW", "AAA", "ACRYLIC BRIDGE", "ACRYLIC CROWN", "ACRYLIC CROWN HEAT CURE", 
    "ACRYLISATION", "ADDING TOOTH", "ADDING TOOTH WITH CLASP", "AGAR AGAR DUPLICATION", 
    "ANTERIOR BITE PLANE", "ANTERIOR FIXED BITE PLANE WITH MOLAR TUBES", "ANTERIOR REPOSITIONING SPLINT", 
    "BANDED HYRAX RME", "BANDED HYRAX RME WITH MOLAR TUBE", "BEGGS RETAINER LOWER", 
    "BEGGS RETAINER UPPER", "BITE PLANE", "BITE RIM LOWER", "BITE RIM U/L", "BITE RIM UPPER", 
    "BLEACHING TRAY", "BLEACHING TRAY BOX", "BONDED HYRAX RME", "BONDED HYRAX RME WITH FACE MASK", 
    "BPS PROBASE", "CAST PARTIAL [CC PLATE]", "CAST PARTIAL BITE RIM", "CAST PARTIAL RPD TRIAL", 
    "CATLAN'S APPLIANCE LOWER", "CD TRIAL U/L", "CERAMIC", "CERAMIC REPAIR", "CLEAR ALIGNER LOWER", 
    "CLEAR ALIGNER SCAN", "CLEAR ALIGNER UPPER", "CLEAR ALIGNER UPPER AND LOWER", "CLEAR RETAINER CUTTING", 
    "CLEAR RETAINER LOWER", "CLEAR RETAINER U/L", "CLEAR RETAINER UPPER", "CLEAR RETAINER WITH BITE PLANE", 
    "COLD CURED BITE SPLINT", "COMPLETE DENTURE", "DENTURE BITE RIM", "DENTURE CORRECTION", 
    "DENTURE CRACK REPAIR", "DENTURE GRINDING", "DENTURE LOWER TRIAL", "DENTURE POLISHING", 
    "DENTURE POLISHING & SMOOTHING", "DENTURE REPAIR", "DENTURE REPAIR - LOWER", "DENTURE REPAIR - UPPER", 
    "DENTURE REPAIR AND POLISHING", "DENTURE UPPER TRIAL", "E MAX", "EMAX", "EMAX VENEER", 
    "EXPANSION SCREW", "EXPANSSION SCREW ADDITION", "FIXED LABIAL BOW WITH HOOKS", "FIXED LINGUAL ARCH", 
    "FIXED TWIN BLOCK WTH HYRAX", "FLEXIBLE CD RELINING", "FLEXIBLE DENTURE ACRYLIZATION", 
    "FLEXIBLE DENTURE BITE L", "FLEXIBLE DENTURE BITE U", "FLEXIBLE DENTURE LOWER", 
    "FLEXIBLE DENTURE SPL TRAY & BITE UL", "FLEXIBLE DENTURE TRIAL L", "FLEXIBLE DENTURE TRIAL U", 
    "FLEXIBLE DENTURE TRIAL U/L", "FLEXIBLE DENTURE U/L", "FLEXIBLE DENTURE UPPER", 
    "FLEXIBLE L/DENTURE RELINING", "FLEXIBLE RELINING", "FLEXIBLE RPD", "FLEXIBLE RPD BITE", 
    "FLEXIBLE RPD REPAIR", "FLEXIBLE RPD TRIAL", "FLEXIBLE TEETH ADDING", "FLEXIBLE U/DENTURE RELINING", 
    "HABIT BREAKER FIXED", "HABIT BREAKER REMOVABLE", "HARD SPLINT LOWER", "HARD SPLINT U/L", 
    "HARD SPLINT UPPER", "HAWLEY'S APLIANCE WITH EXPANSION SCREW", "HAWLEY'S APPLIANCE", 
    "HAWLEY'S APPLIANCE CLEANING", "HAWLEY'S APPLIANCE L", "HAWLEY'S APPLIANCE U", 
    "HAWLEY'S APPLIANCE U/L", "HAWLEY'S APPLIANCE WITH ONE TEETH", "HAWLEY'S APPLIANCE WITH SOLDERED ADAMS", 
    "HAWLEY'S APPLIANCE WITH Z SPRING", "HAWLEY'S APPLIANCE WITH Z SPRING & POSTERIOR BITE PLANE", 
    "HAWLEY'S REPAIR", "HAWLEY'S WITH EXPANSION SCREW & TONGUE GRIP", "HAWLEY'S WITH TONGUE GUARD", 
    "HAWLYS APPLIANCE WITH ANTERIOR BITEPLANE", "HEAD GEAR TUBE SPLINT", "IMPLANT PFM", "IMPRESSION TRAY", 
    "IN LAY", "JACK SCREW WITH LABIAL BOW", "LABIALBOW CLASP", "LINGUAL ARCH", 
    "LINGUAL ARCH WITH MOLAR TUBES", "LINGUAL ARCH WITH RPD", "LINGUAL METAL LOOPS", 
    "LIP BUMPER WITH MOLAR TUBES", "LIP PUMBER LOWER ARCH", "LOWER DENTURE", "LOWER DENTURE TRIAL", 
    "MARYLAND", "METAL BAR FOR IMPLANT DENTURE LOWER", "METAL BAR FOR IMPLANT DENTURE U/L", 
    "METAL BAR FOR IMPLANT DENTURE UPPER", "METAL COPING", "METAL CROWN", "METAL TRIAL", 
    "METAL TRIAL IMPLANT", "MICHIGAN SPLINT", "MODEL PRINT LOWER", "MODEL PRINT U/L", 
    "MODEL PRINT UPPER", "MODEL PRINTING", "MOLAR TUBE", "MONILITHIUM", "MONOBLOCK LABIAL BOW", 
    "MORDEN DESING", "MSE EXPANTION SCREW SOLDERED", "NANCE APPLIANCE", "NANCE APPLIANCE WITH MOLAR TUBES", 
    "NIGHT GUARD LOWER", "NIGHT GUARD U/L", "NIGHT GUARD UPPER", "ON LAY", "ORTHO FACE MASK", 
    "ORTHO RETRACTOR", "ORTHO WIRE MESH", "PENDULUM APPLIANCE", "PFM", "PFM (PRECIOUS)", 
    "PFM BISQUE TRIAL", "PICKUP CHARGES", "PMMA", "PNDULUM APPLIANCE", "POST CORE", 
    "POSTERIOR BITE PLANE", "POSTERIOR BITE PLANE WITH 2D EXPANSION SCREW", 
    "POSTERIOR BITE PLANE WITH FACE MASK", "PROBASE", "QUAD HELIX WITH BUCCAL TUBES AND BANDS", 
    "RE TRIAL", "RELINING", "RELINING & POLISHING", "RPD", "RPD BITE RIM LOWER", "RPD BITE RIM UPPER", 
    "RPD BITE RIM UPPER AND LOWER", "RPD LOWER", "RPD RELINING", "RPD REPAIR", "RPD REPAIR - LOWER", 
    "RPD REPAIR - UPPER", "RPD REPAIR AND ADD TEETH", "RPD REPAIR AND POLISHING", 
    "RPD REPAIR WITH CERAMIC TEETH", "RPD TRIAL L", "RPD TRIAL U", "RPD TRIAL U/L", "RPD UPPER", 
    "RPD WITH CLEAR RETAINER", "RPD WITH MOLAR BANDS AND LINGUAL ARCH", "RPD WITH SAPCE MAINTAINER", 
    "SILICON BITE SPLINT", "SILICON DUPLICATION", "SNAP ON SMILE", "SNAP ON SMILE L", "SNAP ON SMILE U", 
    "SNAP ON SMILE U/L", "SOFT DENTURE U/L", "SOFT SPLINT LOWER", "SOFT SPLINT U/L", "SOFT SPLINT UPPER", 
    "SOLDERED TPA MOLAR TUBE", "SOLDERING", "SPACE MAINTAINER", "SPACE MAINTAINER LOWER", 
    "SPACE MAINTAINER REPAIR", "SPACE REGENERATOR", "SPECIAL TRAY", "SPECIAL TRAY AND BITE L", 
    "SPECIAL TRAY AND BITE U", "SPECIAL TRAY AND BITE U/L", "SPECIAL TRAY L", "SPECIAL TRAY LOWER", 
    "SPECIAL TRAY U", "SPECIAL TRAY U/L", "STL", "STL FILE", "STL FILE U/L", "STUDY MODEL", 
    "TEMPORARY BRIDGE", "TEMPORARY CROWN", "TEMPORARY MARYLAND", "TONGUE GUARD", 
    "TONGUE GUARD WITH MOLAR TUBE", "TRIAL", "TRIPLEX POURABLE", "TWIN BLOCK LOWER", 
    "TWIN BLOCK POLISHING", "TWIN BLOCK REPAIR", "TWIN BLOCK U/L", "TWIN BLOCK UPPER", 
    "TWIN BLOCK WITH EXPANSSION SCREW", "TWIN BLOCK WITH HEAD GEAR", "TWIN BLOCK WITH Z SPRING", 
    "TWO WAY EXPASIION SCREW", "UPPER DENTURE", "UPPER DENTURE TRIAL", "VENEER", "VENEER TRIAL", 
    "WAXUP", "Z SPRING WITH POSTERIOR BITE PLANE", "ZIG TRIAL", "ZIRCON", "ZIRCON BISQUE TRIAL", 
    "ZIRCON CORE", "ZIRCON CORE CUTBACK", "ZIRCON CORE TRIAL", "ZIRCON FULL CROWN", "ZIRCON IMPLANT", 
    "ZIRCON MARYLAND", "ZIRCON POST", "ZIRCON REPAIR", "ZIRCON VENEER", "ZIRCON VENEER CORE TRIAL", 
    "ZIRCON VENEER TRIAL"
  ];

  for (const name of productsRaw) {
    let type = "General";
    if (name.includes("PFM")) type = "PFM";
    else if (name.includes("ZIRCON")) type = "ZIRCONIA";
    else if (name.includes("EMAX") || name.includes("E MAX")) type = "E-MAX";
    else if (name.includes("DENTURE")) type = "DENTURE";
    else if (name.includes("ORTHO") || name.includes("RETAINER") || name.includes("HAWLEY")) type = "ORTHO";
    else if (name.includes("SPLINT") || name.includes("GUARD")) type = "SPLINT";
    else if (name.includes("IMPLANT")) type = "IMPLANT";
    else if (name.includes("TRIAL")) type = "METAL TRAIL";
    else if (name.includes("RPD")) type = "DURAFLEX PARTIAL DENTURE";
    else if (name.includes("FLEXIBLE")) type = "FLEXIBLE";
    else if (name.includes("ACRYLIC")) type = "ACRYLIC";
    
    await prisma.product.create({
      data: {
        name,
        type,
        charge: 0 // Default charge
      }
    });
  }

  console.log('Seeding completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
